feat: 누적신고 5개 이상 게시글 block 기능 구현
woowacourse-teams/2022-sokdak pull request #233
Opened 2022-08-01 08:26 UTC by hyunrrr

### 구현기능
누적신고 5개 이상 게시글 block 기능 구현

### 세부 구현기능
- [ ]: 특정 게시판 모든 글 가져오는 기능에서 누적신고 5개 이상인 게시글은 block
- [ ]: 특정 게시글 가져오는 기능에서 누적신고 5개 이상인 게시글은 block

2022-08-01 08:52 UTC, BETTERFUTURE4 requested changes
조시 수고했습니다~

2022-08-01 08:52 UTC, BETTERFUTURE4 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
> +    private void reportPostToBlockPost(Long postId) {
기존 메서드명도 괜찮긴 한데
메서드명을 `blockPost`로 하는건 어떨까요?
의미가 더 명확해질 것 같아요.

2022-08-01 08:52 UTC, BETTERFUTURE4 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
> +    @DisplayName("게시글 목록 중 누적 신고가 5개 이상인 게시글은 blocked 왼다.")
오타 있네요ㅋㅋ

2022-08-01 08:52 UTC, BETTERFUTURE4 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/report/domain/PostReport.java
> +        this.post.getPostReports().add(this);
이건 그냥 제안인데
해시태그 때 그랬던 것 처럼 신고 관련 기능들만 따로 패키지를 분리하는 방향도 있을 것 같아요.

지금은 기능이 크지 않아서 괜찮은데
나중에 신고 관련해서 기능들이 추가되면 패키지 분리하면 좋을 것 같습니다!

2022-08-01 08:52 UTC, BETTERFUTURE4 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
> +        }
👍

2022-08-03 05:41 UTC, closed without merging

2022-08-03 05:47 UTC, hyunrrr commented
깃 오류 이전에 dev에서 코드를 fetch, rebase했습니다. 이후에 혹시모를 오류발생이 생길지 몰라(최신코드누락) pr을 닫고 새로운 pr을 열어 최신 dev브랜치로부터 기능을 다시 구현하도록 하겠습니다.