feat: 블라인드 된 게시글의 작성자 닉네임 응답값 수정
woowacourse-teams/2022-sokdak pull request #537
Opened 2022-08-26 08:23 UTC by Byeongju-Kong

### 구현기능
블라인드 된 게시글 작성자 닉네임의 응답값이 원래 작성자 닉네임이었는데, 이를 블라인드 처리되었다는 메시지로 수정
또한, 게시글과 댓글의 블라인드 메시지를 변경했습니다.

2022-08-27 01:46 UTC, injoon2019 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java
> +    @DisplayName("신고가 5개 이상이면 isBlocked()가 false를 반환하고 게시글 정보들이 반환된다.")
`5개 미만`으로 고쳐야할 것 같습니다!

2022-08-27 01:47 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
> +    private static final String BLIND_MESSAGE = "블라인드 처리된 게시글입니다.";
위에서 댓글 블라인드 처리를 `BLIND_COMMENT_MESSAGE`라 했으니 `BLIND_POST_MESSAGE`라고 하는게 더 통일감 있을 것 같아요!

2022-08-27 01:48 UTC, injoon2019 requested changes
크리스 수고하셨습니다~ 리팩토링 해주셨네요! 간단한 코멘트 남겼는데 확인해주세요!

2022-08-28 06:35 UTC, Byeongju-Kong commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java
> +    @DisplayName("신고가 5개 이상이면 isBlocked()가 false를 반환하고 게시글 정보들이 반환된다.")
그렇네요!! 수정했습니다~

2022-08-28 06:36 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
> +    private static final String BLIND_MESSAGE = "블라인드 처리된 게시글입니다.";
좋습니다~!

2022-08-28 06:49 UTC, injoon2019 approved these changes
크리스 수고하셨습니다~

2022-08-28 07:18 UTC, merged