refactor: Notification 리팩토링
woowacourse-teams/2022-sokdak pull request #584
Opened 2022-09-27 15:05 UTC by Byeongju-Kong

### 구현기능
- notification 조회시 반복문을 돌면서 query문을 실행하는 로직, where~in으로 개선
- comment와 post에 해당하는 Notification 삭제 로직에서 query문이 Notification의 개수만큼 실행되는 문제 where~in으로 개선

#576

2022-09-29 06:49 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
> +    }
쿼리 수 많이 줄일 수 있겠네요! 굿!

2022-09-29 07:31 UTC, injoon2019 requested changes
안녕하세요 크리스~ 

몇몇 가지들은 변경 사항은 아니지만 기존 코드를 읽다가 헷갈렸던 부분들이 있어 남겨봅니다!

1. `notify()` 메서드가 실제로는 notification을 저장하는 역할을 하고 있는데요 `saveNotification`은 어떤가요? (notifyHotBoard(), notifyCommentReport().. 등등도요!)

2. `findNotifications()` 메서드명이 조금 헷갈렸어요. 일반적으로 findXXXs면 JPA에서 조회의 형태로 사용되는데, 조회했다는 상태의 변경이 일어나더라고요. 그래서 조금 헷갈렸습니다. 

3. `inquireNotification`도 비슷한대요, 뜻 그대로 알림을 조회하는 줄 알았는데 상태를 조회하더라고요. change를 명백히 나타내는건 어떤가요?

2022-09-29 07:31 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java
> +            nativeQuery = true)
키워드들을 다 대문자로 쓰고 있는 것 같은데 혼용되어있는 부분도 있네요. `where`, `in`도 다 대문자로 적는게 컨벤션으로 알고 있습니다! 나머지 쿼리들도 마찬가지요!

2022-09-29 07:31 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
>      @Transactional(readOnly = true)
보통 클래스 레벨에 `readOnly` 트랜잭션을 걸고 메서드에 `@Transactional`을 쓰잖아요. 반대로 하신 이유가 있으신가요?

2022-09-29 07:31 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
>      private void inquireNotification(List<Notification> notifications) {
메서드 명을 notifications로 해주는건 어떤가요?

2022-09-29 07:31 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
> +        notificationRepository.inquireNotificationByIds(inquiredNotificationIds);
이거 궁금한게 jpa니까 예전 방식대로 for문을 이용해서 각각의 notification의 상태만 inquire로 바꿔주면 쓰기지연저장소에 있다가 알아서 변경상태가 반영되지 않나요?

2022-09-29 07:50 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
> +        notificationRepository.inquireNotificationByIds(inquiredNotificationIds);
그렇게 하면 하나의 엔티티당 하나의 update 쿼리가 실행되어서 이렇게 변경했습니다~!

2022-09-29 07:53 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
>      private void inquireNotification(List<Notification> notifications) {
그 방면이 좋겠네요~ 수정했습니다!

2022-09-29 08:09 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java
> +            nativeQuery = true)
수정했습니당~!

2022-09-30 05:48 UTC, injoon2019 approved these changes
고생하셨습니다!

2022-09-30 05:49 UTC, merged