refactor: like 패키지 리팩토링
woowacourse-teams/2022-sokdak pull request #597
Opened 2022-09-30 06:59 UTC by Byeongju-Kong

### 구현기능
like 패키지 리팩토링

### 세부 구현기능
- [ ] Service와 Repository에서의 쿼리 개선
- [ ] Like 워딩을 PostLike으로 수정
- [ ] like 패키지의 전반적인 코드 품질 개선
- [ ] like 패키지의 테스트 리팩토링 및 부족한 테스트 추가

### 관련 이슈
DB 테이블 컬럼명 변경 필요 #596

2022-09-30 07:28 UTC, injoon2019 requested changes
크리스 네이밍 수정 잘 해주셨네요~

2022-09-30 07:28 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java
> +    private void flipPost(Member member, Post post) {
flipPostlike()가 더 적절하지 않을까요!

2022-10-04 07:20 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java
> +    private void flipPost(Member member, Post post) {
확인했습니당~!

2022-10-04 08:29 UTC, injoon2019 approved these changes

2022-10-04 08:38 UTC, merged