Feature/620 5th
woowacourse-teams/2022-sokdak pull request #630
Opened 2022-10-13 06:04 UTC by hyunrrr

### 구현기능
5기 지원자들을 위한 게시판 기능 구현

### 세부 구현기능
- [ ] 5기 지원자를 위한 새로운 role 만들기
- [ ] 5기 지원자 role로 회원가입하기
    - [ ] 이메일 인증 필요 없음
- [ ] 5기 게시판
    - [ ] 글 읽기는 로그인 안해도 가능
    - [ ] 글 쓰기는 로그인 하면 모두 가능
- [ ] 기존 게시판들
    - [ ] 글 읽기는 로그인 안해도 가능
    - [ ] 글 쓰기는 로그인 한 회원 중 USER, ADMIN만 가능

2022-10-13 06:10 UTC, byhhh2 commented
PR 제목 점검 바랍니당~

2022-10-14 08:44 UTC, injoon2019 requested changes
조시 고생많으셨습니다. 리뷰 반영 드렸으니 보시고 혹시 이해안되는 부분 있으면 알려주세요!

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/auth/service/AuthServiceTest.java
> +    }
good!

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/support/ApplicantInterceptor.java
> +        System.out.println("enter@@@@@@@@@@@@@");
sout 삭제해주세요~

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/support/ApplicantInterceptor.java
> +        System.out.println(RoleType.APPLICANT.getName());
마찬가지로 삭제해주세요~

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/support/ApplicantInterceptorTest.java
> +        assertThat(response.statusCode()).isNotEqualTo(HttpStatus.FORBIDDEN.value());
이거 unauthorized/forbidden 확인 한번만해주세요! 맞으면 수정 안하셔도됩니다!

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
> +        }
이게 무슨 로직일까요?

2022-10-14 08:44 UTC, injoon2019 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
> +    }
good!

2022-10-16 03:34 UTC, hyunrrr commented on backend/sokdak/src/main/java/com/wooteco/sokdak/member/controller/MemberController.java
>          memberService.signUp(signupRequest);
헉 그러네요.. 버그 생길뻔했네요..

2022-10-16 03:36 UTC, hyunrrr commented on backend/sokdak/src/main/java/com/wooteco/sokdak/support/ApplicantInterceptor.java
> +        System.out.println("enter@@@@@@@@@@@@@");
인터셉터 삭제되어서 아마 최종 코드에는 없을거에요!

2022-10-16 03:36 UTC, hyunrrr commented on backend/sokdak/src/main/java/com/wooteco/sokdak/support/ApplicantInterceptor.java
> +        System.out.println(RoleType.APPLICANT.getName());
인터셉터 삭제되어서 아마 최종 코드에는 없을거에요!

2022-10-16 03:39 UTC, hyunrrr commented on backend/sokdak/src/test/java/com/wooteco/sokdak/support/ApplicantInterceptorTest.java
> +        assertThat(response.statusCode()).isNotEqualTo(HttpStatus.FORBIDDEN.value());
인터셉터 테스트인데 인터셉터 삭제하면서 테스트도 최종코드에는 없앴습니다!!

2022-10-16 03:51 UTC, hyunrrr commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
> +        }
메서드 분리하고 로직 좀 더 명확하게 바꿔보았습니다!

2022-10-16 11:44 UTC, injoon2019 approved these changes

2022-10-16 11:44 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
> +    }
가독성이 훨씬 좋아졌네요! 좋습니다!

2022-10-16 11:48 UTC, merged