refactor: 암호화 static을 빈 형태로 리팩토링
woowacourse-teams/2022-sokdak pull request #634
Opened 2022-10-13 12:53 UTC by BETTERFUTURE4

### 구현기능
resolved: #536 

### 세부 구현기능

### 관련 이슈

2022-10-17 12:08 UTC, Byeongju-Kong requested changes
헌치! 고생하셨습니다~! 리뷰 확인해주세요~

2022-10-17 12:08 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
> +        this.password = new Password(EncryptorFactory.encryptor(), password);
static 메서드를 통해서 값 객체에 주입하셨네요!

MemberService에서 Encoder를 DI 받고, Member의 정적팩토리에 Encoder를 넣고, 이를 Username과 Password의 정적팩토리로 주입시켜주는 방식은 어떨까요?
제가 알기론, Bean을 싱글턴으로 관리되기 때문에 static 접근으로 잘 얻지 않는 것으로 알고 있어요.

2022-10-17 12:08 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
> +        this.password = new Password(EncryptorFactory.encryptor(), password);
또한, Username과 Password 생성 전략이 정적팩토리면 더욱 좋을 것 같네요~!

2022-10-17 12:09 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/domain/encryptor/Encryptor.java
> +}
Encoder를 Encrytor로 wrapping한 이유가 있으신가요? Encoder만 사용해도 충분히 문제가 없어보입니다!

2022-10-18 06:50 UTC, BETTERFUTURE4 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/domain/encryptor/Encryptor.java
> +}
Encoder만 사용하도록 코드 수정했습니다!

2022-10-18 06:50 UTC, BETTERFUTURE4 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/auth/domain/encryptor/EncryptorFactory.java
> +}
테스트에만 사용되는 static 필드를 제거 후 테스트용 픽스처로 대체했습니다!

2022-10-18 07:06 UTC, BETTERFUTURE4 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
> +        this.password = new Password(EncryptorFactory.encryptor(), password);
Username, Password 주입을 바깥에서 정적 팩토리 메소드로 진행하고, 테스트에서는 픽스처를 사용하는 방식으로 변경했습니다!

2022-10-18 07:15 UTC, Byeongju-Kong approved these changes

2022-10-18 07:46 UTC, merged