645 search
woowacourse-teams/2022-sokdak pull request #654
Opened 2022-10-18 02:39 UTC by BETTERFUTURE4

### 구현기능

### 세부 구현기능

### 관련 이슈

2022-10-18 02:53 UTC, Byeongju-Kong requested changes
헌치! 일단 String query를 객체로 먼저 분리해보시면 좋을 것 같아요!

2022-10-18 02:53 UTC, Byeongju-Kong commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
> +        return query;
query를 객체로 만들어보는건 어떨까요?

2022-10-18 02:53 UTC, Byeongju-Kong commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
> +        postRepository.save(post3);
```suggestion
        Post post1 = Post.builder()
                .title("제목")
                .content("본문")
                .member(member)
                .build();
        Post post2 = Post.builder()
                .title("제목2")
                .content("본문2검색")
                .member(member)
                .build();
        Post post3 = Post.builder()
                .title("제목2검색")
                .content("본문2")
                .member(member)
                .build();
        postRepository.saveAll(List.of(post1, post2, post3));
```

2022-10-18 08:01 UTC, BETTERFUTURE4 commented on backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
> +        postRepository.save(post3);
한꺼번에 저장되도록 수정했습니다!

2022-10-20 11:41 UTC, hyunrrr approved these changes

2022-10-20 11:52 UTC, Byeongju-Kong approved these changes

2022-10-20 11:53 UTC, merged