feat: 조회수 기능(어뷰징 방지 안됨)
woowacourse-teams/2022-sokdak pull request #686
Opened 2022-10-19 07:42 UTC by hyunrrr

### 구현기능
조회수 기능(어뷰징 방지 안됨)
특정 포스트를 조회하면 조회수가 증가한다.

2022-10-19 08:13 UTC, injoon2019 requested changes
조시 기능 잘 구현하신 것 같은데 리뷰 확인해주세요!

2022-10-19 08:13 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
개행 두줄 들어갔어요!

2022-10-19 08:13 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
> +    private ViewCount viewCount = new ViewCount();
여기에는 왜 `new ViewCount()`로 바로 넣어주나요?

2022-10-19 08:13 UTC, injoon2019 commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/ViewCount.java
> +    private int viewCount = 0;
이거 동시성 이슈 없을까요?

2022-10-19 08:14 UTC, hyunrrr commented on backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
> +    private ViewCount viewCount = new ViewCount();
외부에서 주입받을 필요가 없는 필드이기 때문에 바로 생성되도록 했습니다.

2022-10-20 11:29 UTC, injoon2019 approved these changes
확인했습니다~

2022-10-20 12:18 UTC, merged